name: Move to Awaiting Review - v1.1
on:
  label:
    types: [created, edited]
  workflow_dispatch:

jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Project Automation+
        uses: alex-page/github-project-automation-plus@v0.8.2
        if: ${{ github.event.label.name == 'Awaiting Review' && github.event.label.name == 'v1.1' }}
        with:
          project: v1.1
          column: Awaiting Review
          repo-token: ${{ secrets.BEWDSC_ACCESS_TOKEN }}
