name: Move to Awaiting Review - v1.1
on:
  issues:
    types: [labeled]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.1
        with:
          repository: 'DSC-iTC/cPP'
      - name: handle input  
        id: set-matrix
        run: |
          sudo bash script.sh ${{ inputs.labelsJson }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Project Automation+
        #if: ${{ github.event.label.name == 'Awaiting Review' && github.event.label.name == 'v1.1' }}
        uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          project: ${{ matrix.project }}
          column: 'Awaiting Review'
          repo-token: ${{ secrets.BEWDSC_ACCESS_TOKEN }}
